version: '3'

volumes:
  mydjango_local_postgres_data: {}
  mydjango_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mydjango_local_django
    container_name: mydjango_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mydjango_production_postgres
    container_name: mydjango_local_postgres
    volumes:
      - mydjango_local_postgres_data:/var/lib/postgresql/data:Z
      - mydjango_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  frontend:
    container_name: frontend
    restart: always
    build:  
      context: ./front-end
      dockerfile: Dockerfile
    image: myproj_frontend_image
    depends_on:
      - django
    volumes:
      - ./front-end/nginx:/etc/nginx/conf.d
    ports:
      - 81:80